import CFG


def test_ai_value():
    """
    Tests the assembly calculator's result for the input string "abracadabra".

    The function verifies that the assembly calculator produces the expected result
    for the given input string.

    Asserts:
        - The assembly calculator result matches the expected result.

    Raises:
        AssertionError: If the assertion fails.
    """
    # Test input string
    s_inpt = "abracadabra"
    # Get the assembly calculator result
    ai, _ = CFG.ai_core(s_inpt)
    # Assembly calculator result gives 7
    ai_ref = 7
    # Check if the result is correct
    assert ai == ai_ref


def test_virt_obj():
    """
    Tests the consistency and correctness of virtual objects generated by the assembly calculator.

    The function verifies that the virtual objects produced by the `ai_with_pathways` function:
        - Are substrings of the input string.
        - Match a predefined reference list of virtual objects.
        - Have the expected size.

    Asserts:
        - Each virtual object is a substring of the input string.
        - Each virtual object matches an object in the reference list.
        - The total number of virtual objects matches the expected size.

    Raises:
        AssertionError: If any of the assertions fail.
    """
    # Test input string
    s_inpt = "abracadabra"
    # Get the result
    _, virt_obj, _ = CFG.ai_with_pathways(s_inpt)
    virt_obj_ref = ['d', 'c', 'b', 'r', 'a', 'ab', 'abr', 'abra', 'abrac', 'abraca', 'abracad']
    # Check that the virtual objects are consistent with the input string
    for obj in virt_obj:
        assert obj in s_inpt
    # Check that the virtual objects are consistent with the reference
    for obj in virt_obj:
        assert obj in virt_obj_ref
    # Check that the virtual objects are a set size
    assert len(virt_obj) == 11


def test_path():
    """
    Tests the pathway generation and graph structure of the assembly calculator.

    The function verifies that the `ai_with_pathways` function produces a path with the
    expected number of nodes and edges for the given input string.

    Asserts:
        - The path contains 12 nodes.
        - The path contains 14 edges.

    Raises:
        AssertionError: If any of the assertions fail.
    """
    # Test input string
    s_inpt = "abracadabra"
    # Get the assembly calculator result
    _, _, path = CFG.ai_with_pathways(s_inpt, f_print=False)
    # Assert that the path has 12 nodes
    assert len(path) == 12
    # Assert that there are 14 edges
    assert len(path.edges) == 14


def test_batch():
    """
    Tests the assembly calculator's results for a batch of input strings.

    The function verifies that the assembly calculator produces the expected results
    for multiple input strings by comparing the calculated results with the expected values.

    Asserts:
        - The assembly calculator result matches the expected result for each input string.

    Raises:
        AssertionError: If any of the assertions fail.
    """
    # Test input strings
    s_inpts = ["abracadabra", "aaaaaaa", "ababcdcd"]
    # Expected assembly calculator results
    ai_refs = [7, 4, 5]
    for i in range(len(s_inpts)):
        # Get the assembly calculator result
        ai, virt_obj, _ = CFG.ai_with_pathways(s_inpts[i], f_print=False)
        # Check if the result AI is correct
        assert ai == ai_refs[i]
        # Check that the virtual objects are consistent with the input string
        for obj in virt_obj:
            assert obj in s_inpts[i]


def test_joint():
    """
    Tests the assembly calculator's results for a set of input strings.

    The function verifies that the assembly calculator produces the expected results
    for a set of input strings by comparing the calculated results with the expected values.

    Asserts:
        - The assembly calculator result matches the expected result for the set of input strings.

    Raises:
        AssertionError: If any of the assertions fail.
    """
    # Test input strings
    s_inpt = "aaaadbbbbcaa"
    # Expected assembly calculator result
    ai_ref = 8
    # Get the assembly calculator result
    ai, virt_obj, _ = CFG.ai_with_pathways(s_inpt, f_print=True, debug=True)
    # Check if the result is correct
    assert ai == ai_ref


def test_joint2():
    s_in = ["aaaa", "bbbbcaa"]

    ai_ref = 6
    ai, virt_obj, _ = CFG.ai_with_pathways(s_in, f_print=True, debug=True)
    assert ai == ai_ref
