import CFG


def test_abracadabra():
    """
    Tests the assembly calculator's result for the input string "abracadabra".

    The function verifies that the assembly calculator produces the expected result
    for the given input string.

    Asserts:
        - The assembly calculator result matches the expected result.

    Raises:
        AssertionError: If the assertion fails.
    """
    # Test input string
    s_inpt = "abracadabra"
    # Get the assembly calculator result
    ai, _ = CFG.ai_core(s_inpt)
    # Assembly calculator result gives 7
    ai_ref = 7
    # Check if the result is correct
    assert ai == ai_ref


def test_virt_obj():
    """
    Tests the consistency of virtual objects generated by the assembly calculator.

    The function uses a predefined input string to verify that the virtual objects
    produced by the `ai_with_pathways` function are consistent with the input string.

    Asserts:
        - Each virtual object is a substring of the input string.

    Raises:
        AssertionError: If any of the assertions fail.
    """
    # Test input string
    s_inpt = "abracadabra"
    # Get the result
    ai, virt_obj, path = CFG.ai_with_pathways(s_inpt)
    # Check that the virtual objects are consistent with the input string
    for obj in virt_obj:
        assert obj in s_inpt


def test_path():
    """
    Tests the assembly calculator's pathway generation and final path consistency.

    The function uses predefined input strings and their expected assembly calculator results
    to verify the correctness of the pathway generation and the final path produced by the
    `ai_with_pathways` function.

    Asserts:
        - The assembly calculator result matches the expected result.
        - The length of the generated path matches the expected result.
        - The final path matches the input string.

    Raises:
        AssertionError: If any of the assertions fail.
    """
    # Test input strings
    s_inpts = ["abracadabra", "aaaaaaa", "ababcdcd"]
    # Assembly calculator results
    ai_refs = [7, 4, 5]
    for i in range(len(s_inpts)):
        # Get the assembly calculator result
        ai, _, path = CFG.ai_with_pathways(s_inpts[i], f_print=False)
        # Get the final path
        final_path = path[-1].split(" = ")[1].strip()
        # Check if the result is correct
        assert ai == ai_refs[i]
        assert len(path) == ai_refs[i]
        assert final_path == s_inpts[i]
